// flow-typed signature: bd6945346e0f41b00d9c72a9e994c34e
// flow-typed version: <<STUB>>/find-up_v^3.0.0/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'find-up'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'find-up' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'find-up/index' {
  declare module.exports: $Exports<'find-up'>;
}
declare module 'find-up/index.js' {
  declare module.exports: $Exports<'find-up'>;
}
