// flow-typed signature: aaf85b08d6483f778256fdde8bfbd735
// flow-typed version: <<STUB>>/koa-webpack_v^5.1.1/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-webpack/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-webpack/lib/index.js' {
  declare module.exports: $Exports<'koa-webpack/lib/index'>;
}
